### ISSUE TITLE
Tunnel Closing Immediately

### ISSUE THREAD

**Issue by piyushchhabra** [jweslley/localtunnel#1]
I am trying to open a tunnel for 1 minute and then close it but I am getting error "Close of alredady closed channel" . 

Infact If I dont close it, Its imeediately closing my tunnel just after creation, Can you please help ?

func main() {
	os.Setenv("HTTP_PROXY", "myNetworkProxyIp:80")
	port := 8080
	tunnel := localtunnel.NewLocalTunnel(port)
	err := tunnel.Open()
	if err != nil {
		panic(err)
	}
	fmt.Printf("your url is: %s\n", tunnel.URL())
	time.Sleep(time.Millisecond * 60000)
	tunnel.Close()
}

**Comment by jweslley** [comment]
Hi @piyushchhabra , did you get it to work?
